project:
  type: website

website:
  page-footer: 
    center: |
      Compiled by
        [![](Posit-Logos-2024_horiz-full-color.svg){fig-alt="Posit" width=65px}](https://posit.co)
      | 
      Built with [Quarto](http://quarto.org)

format: 
  html:
    theme: [cosmo, styles.scss]
    toc: false
